---
name: "ncm_config_download"
pack: "orion"
description: "Download NCM configs for a node."
action_ref: "orion.ncm_config_download"
formats:
  - display: "orion ncm config-download {{node}}"
    representation:
      - "orion ncm config-download {{node}}"
ack:
  enabled: true
  append_url: false
  format: "Downloading NCM config's for {{ execution.parameters.node }} you..."
result:
  format: |
    {% if execution.status == 'succeeded' %}
    Orion NCM Download of {{ execution.parameters.node }} has been successful!{~}
    {% for item, value in execution.result.result.iteritems() %}
    *{{item}}:* {{value.status}}
    {% endfor %}
    {% else %}
    Error downloading Orion NCM config: {{execution.result.stdout}}{~}See {{execution.id}} for more details.
    {% endif %}
